### PR TITLE
added timer-and-stopwatch

### PR DESCRIPTION
**Pull request by Sisir2311**

### CODE REVIEW

**Comment by Sisir2311** [comment]
It worked on my system bro once check from your side 😈

**Comment by iamwatchdogs** [comment]
Sorry for the inconvenience @Sisir2311. The linter config has been updated and working fine. Please make a commit by adding a comment to any of your js files, to perform the lining checks.

**Review by iamwatchdogs — APPROVED** [review]
Reviewed and Approved by @iamwatchdogs.

**Comment by iamwatchdogs** [comment]
Thank you for contributing, @Sisir2311. Please check your contribution on [GitHub Pages](https://grow-with-open-source.github.io/Javascript-Projects/).

**Pull request merged**
